{
 "title": "Jenkins Pipeline Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Pipeline", "query": "label_values(folder)" }
  ]
 },
 "panels": [
  {
   "title": "Version Delta",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jenkins:deploydelta:devuat{result=\"successful\",folder=\"$Pipeline\"}",
     "legendFormat": "UAT"
    },
    {
     "expr": "jenkins:deploydelta:devprod{result=\"successful\",folder=\"$Pipeline\"}",
     "legendFormat": "PROD"
    }
   ]
  },
  {
   "title": "Current build in DEV",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "jenkins_custom_last_checkout_build_number{folder=\"$Pipeline\",jenkins_job=\"deploy-dev\",result=\"successful\"}"
    }
   ]
  },
  {
   "title": "Current build in UAT",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "jenkins_custom_last_checkout_build_number{folder=\"$Pipeline\",jenkins_job=\"deploy-uat\",result=\"successful\"}"
    }
   ]
  },
  {
   "title": "Current build in PROD",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "jenkins_custom_last_checkout_build_number{folder=\"$Pipeline\",jenkins_job=\"deploy-prod\",result=\"successful\"}"
    }
   ]
  },
  {
   "title": "Version Time Delta",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "jenkins:deploytimedelta:devuat{result=\"successful\",folder=\"$Pipeline\"}",
     "legendFormat": "UAT"
    },
    {
     "expr": "jenkins:deploytimedelta:devprod{result=\"successful\",folder=\"$Pipeline\"}",
     "legendFormat": "PROD"
    },
    { "expr": "300 ", "legendFormat": "Threshold" }
   ]
  },
  {
   "title": "Last deploy to DEV",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 7 },
   "format": "dateTimeAsUS",
   "valueName": "avg",
   "targets": [
    {
     "expr": "jenkins_last_build_timestamp_seconds{folder=\"$Pipeline\", result=\"successful\", jenkins_job=\"deploy-dev\"} * 1000"
    }
   ]
  },
  {
   "title": "Last deploy to DEV",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 7 },
   "format": "dateTimeAsUS",
   "valueName": "avg",
   "targets": [
    {
     "expr": "jenkins_last_build_timestamp_seconds{folder=\"$Pipeline\", result=\"successful\", jenkins_job=\"deploy-dev\"} * 1000"
    }
   ]
  },
  {
   "title": "Last deploy to PROD",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 7 },
   "format": "dateTimeAsUS",
   "valueName": "avg",
   "targets": [
    {
     "expr": "jenkins_last_build_timestamp_seconds{folder=\"$Pipeline\", result=\"successful\", jenkins_job=\"deploy-prod\"} * 1000"
    }
   ]
  },
  {
   "title": "Current Alerts",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "ALERTS{folder=\"$Pipeline\"}",
     "legendFormat": "{{ $labels.summary }}"
    }
   ]
  },
  {
   "title": "Deploys to DEV in the last 24h",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 14 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "changes(jenkins_last_build_timestamp_seconds{folder=\"$Pipeline\", result=\"successful\", jenkins_job=\"deploy-dev\"}[24h])"
    }
   ]
  },
  {
   "title": "Deploys to UAT in the last 24h",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 14 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "changes(jenkins_last_build_timestamp_seconds{folder=\"$Pipeline\", result=\"successful\", jenkins_job=\"deploy-uat\"}[24h])"
    }
   ]
  },
  {
   "title": "Deploys to PROD in the last 24h",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 14 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "changes(jenkins_last_build_timestamp_seconds{folder=\"$Pipeline\", result=\"successful\", jenkins_job=\"deploy-prod\"}[24h])"
    }
   ]
  }
 ]
}